---
- hosts: localhost
  user: vagrant
  sudo: yes
  tasks:
  - name: apt-get update
    apt: update_cache=yes

  - name: install base
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
      - make
      - gcc
      - python
      - python-setuptools
      - python-software-properties
      - rubygems
      - unzip
      - zip

  - name: install node apt repo
    apt_repository: repo=ppa:chris-lea/node.js state=present

  - name: install node
    apt: pkg=nodejs state=present update_cache=yes
  
  - name: install n
    npm: name=n state=present global=yes
    
  - name: switch to node 0.11.x
    command: n latest
    
  - name: install grunt
    npm: name=grunt-cli state=present global=yes

  - name: install bower
    npm: name=bower state=present global=yes

  - name: install phantom.js
    npm: name=phantomjs state=present global=yes
  
  - name: install ember cli
    npm: name=ember-cli state=present global=yes

  - name: install bundler
    gem: name=bundler state=latest user_install=no

  - name: mongodb | get 10gen apt key
    command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

  - name: mongodb | get 10gen apt repository
    copy: src=files/apt-source-mongodb dest=/etc/apt/sources.list.d/10gen.list mode=755

  - name: mongodb | install
    apt: pkg=mongodb-10gen=2.4.10 state=installed update_cache=yes

